name = "vote-processor"
main = "vote-processor.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/30 * * * *"]

[vars]
# Variables sobrescritas desde el dashboard de CF / wrangler secrets
DATABASE_URL             = ""
UPSTASH_REDIS_REST_URL   = ""
UPSTASH_REDIS_REST_TOKEN = ""
